steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/legal-assistant-backend:v1', '.']
  
  # Push the container image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/legal-assistant-backend:v1']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'legal-assistant-backend'
      - '--image=gcr.io/$PROJECT_ID/legal-assistant-backend:v1'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--set-env-vars=IK_API_KEY=18a7742b111567c20f1f9d59e124e61f8740eab2'

images:
  - 'gcr.io/$PROJECT_ID/legal-assistant-backend:v1'

timeout: 1800s 