[phases.setup]
cmds = [
    ["apt-get", "update"],
    ["apt-get", "install", "-y", "build-essential", "cmake", "pkg-config", "python3-dev"]
]

[phases.install]
cmds = [
    ["pip", "install", "--user", "-r", "requirements.txt"]
]
