services:
  - type: web
    name: legal-assistant-backend
    runtime: python
    plan: free
    pythonVersion: 3.10.0
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: IK_API_KEY
        sync: false
    autoDeploy: true 