services:
  - type: web
    name: legal-assistant-backend
    runtime: python
    plan: free
    pythonVersion: 3.10.0
    buildCommand: pip install numpy==1.24.3 && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: IK_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      memory: 1024Mi 